### PR TITLE
[RoleAssigner] Patch

### PR DESCRIPTION
**Pull request by Injabie3**
### Description of the changes
Assign/unassign roles based on if a user has a specific role assigned to them.

References #68.

### CODE REVIEW

**Review by KamiCreed — APPROVED** [review]
Guess you had to iterate twice, huh? I guess that's one way of doing it. Seems Ok.

**Comment by Injabie3** [comment]
Do you see a more efficient way of doing it?  I'm open to ideas since I took a quick glance at the wrapper API so I might have missed something.  I'll merge it in for now, but would be good to make it better if possible.

**Comment by KamiCreed** [comment]
I don't know. You could probably iterate once and check each user if they have the role specified **and** assign them the role if so. Looking at the code, it seems like you iterate once and filter out by checking the role and then iterate through the rest assigning the role. You could do the assigning during the checking.

**Comment by Injabie3** [comment]
Ah, good point, I'll play around with that and see.  Thanks Kami 🙏 🙏

**Pull request merged**
